name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up .NET environment
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.309'

      # Create PEM file from secret
      - name: Create PEM file
        run: |
          mkdir -p Certificates
          echo "${{ secrets.PEM_FILE_CONTENT }}" > Certificates/floom-gateway-pair.pem
          chmod 600 Certificates/floom-gateway-pair.pem

      # Restore .NET dependencies and build the project
      - name: Restore and Build
        run: |
          CORE_OUTPUT_DIR="./build/Floom.Core"
          BUILD_ARCHIVE="floom_core_build.zip"
          PEM_FILE="Certificates/floom-gateway-pair.pem"

          # Clean up previous build
          rm -rf "./build"
          mkdir -p "$CORE_OUTPUT_DIR/"

          # Restore dependencies
          echo "Restoring dependencies for Floom.Core..."
          dotnet restore "Floom.Core/Floom.Core.csproj"

          # Build and publish Floom.Core project
          echo "Publishing Floom.Core project..."
          dotnet publish "Floom.Core/Floom.Core.csproj" -c Release -o "$CORE_OUTPUT_DIR"

          # Zip the build folder
          echo "Zipping the build artifacts..."
          cd "./build"
          zip -r "../$BUILD_ARCHIVE" "Floom.Core"
          cd ..

      # Upload the build artifact to the remote server and deploy
      - name: Deploy to Remote Server
        run: |
          REMOTE_HOST="${{ secrets.REMOTE_HOST }}"
          REMOTE_DIR="${{ secrets.REMOTE_DIR }}"
          SERVICE_NAME="${{ secrets.SERVICE_NAME }}"
          PEM_FILE="Certificates/floom-gateway-pair.pem"
          BUILD_ARCHIVE="floom_core_build.zip"

          # Copy the zip file to the remote server
          echo "Copying the build archive to the remote server..."
          scp -o StrictHostKeyChecking=no -i "$PEM_FILE" "$BUILD_ARCHIVE" "$REMOTE_HOST:~/"

          # SSH into the remote server to deploy
          ssh -o StrictHostKeyChecking=no -i "$PEM_FILE" "$REMOTE_HOST" bash -c "
            set -e
            echo 'Stopping the service...'
            sudo systemctl stop $SERVICE_NAME

            echo 'Cleaning up old files...'
            sudo rm -rf $REMOTE_DIR/*

            echo 'Creating necessary directories...'
            sudo mkdir -p $REMOTE_DIR

            echo 'Unzipping the new build...'
            sudo unzip -o ~/$BUILD_ARCHIVE -d $REMOTE_DIR

            echo 'Removing any conflicting Floom.Core directory...'
            if [ -f $REMOTE_DIR/Floom.Core ]; then
              sudo rm -f $REMOTE_DIR/Floom.Core
            fi
            if [ -d $REMOTE_DIR/Floom.Core ]; then
              sudo rm -rf $REMOTE_DIR/Floom.Core
            fi

            echo 'Moving files...'
            sudo mv -f $REMOTE_DIR/Floom.Core/* $REMOTE_DIR

            echo 'Removing the now empty Floom.Core directory...'
            sudo rm -rf $REMOTE_DIR/Floom.Core

            echo 'Removing the zip file...'
            rm ~/$BUILD_ARCHIVE

            echo 'Starting the service...'
            sudo systemctl start $SERVICE_NAME

            echo 'Deployment completed.'
          "

          # Clean up local zip file
          rm "$BUILD_ARCHIVE"

        env:
          REMOTE_HOST: "${{ secrets.REMOTE_HOST }}"
          REMOTE_DIR: "${{ secrets.REMOTE_DIR }}"
          SERVICE_NAME: "${{ secrets.SERVICE_NAME }}"
